### ISSUE TITLE
[1.16.3] Client crash on putting item with burn time into fuel slot

### ISSUE THREAD

**Issue by ProsperCraft** [Andromander/Nifty#23]
Crash report-
https://gist.github.com/ProsperCraft/ef1d0180e95cb7ba24d45af02956a133

Latest.log-
https://gist.githubusercontent.com/ProsperCraft/e8a53ad57323b75740ac6d6d107c37b6/raw/3c19ff3a8a38bb4fc91e4423b1f6dbbbfbcafd81/gistfile1.txt

ornamental-1.16.3-4.3
Forge 34.1.25

**Comment by ProsperCraft** [comment]
Reproduced here-
https://gist.github.com/ProsperCraft/8a1178a384ea11fd9309bab0fd369a73

Modpack- [TownCraft TWO](https://www.curseforge.com/minecraft/modpacks/towncraft)

**Comment by Andromander** [comment]
Able to reproduce, however the title is misleading as it requires putting the item into the Furnace in order for the crash to occur. Might be because of another mod that's attempting to read the burn time method earlier than the Furnace, but in an isolated environment, this happens when putting the fuel items into the furnace.

**Comment by Andromander** [comment]
Bug identified and fixed. Will release it ASAP with another fix to a visual glitch.
